### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'gene_models/zea_sol_ara_sor_52.gtf'

### ISSUE THREAD

**Issue by shiyegao** [NAMlab/DeepCRE#1]
When I run ```python train_msr_models_leaf.py```, it returns

```
Traceback (most recent call last):
    gene_model = pd.read_csv('gene_models/zea_sol_ara_sor_52.gtf', sep='\t')
  File "/opt/conda/envs/envd/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/envs/envd/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/envs/envd/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/envs/envd/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/envs/envd/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'gene_models/zea_sol_ara_sor_52.gtf'
```

Can you share the 'gene_models/zea_sol_ara_sor_52.gtf' file?

**Comment by PelFritz** [comment]
Hi @shiyegao  within the models folder is a script called create_super_genome_gtf_tpm_for_msr.py. This script creates combines the combined fasta, gtf and counts files for you. This should solve the problem of the missing zea_sol_ara_sor_52.gtf.

cheers
Fritz

**Comment by shiyegao** [comment]
Thanks, it works!
